version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-api-rest:latest
    container_name: springboot_api_rest
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend_net

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$MYSQL_USER -p$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend_net

volumes:
  mysql_data:
    driver: local

networks:
  backend_net:
    driver: bridge
